version: 2

jobs:
    build:
      docker:
        - image: circleci/node:8
      steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Npm login
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
            name: precompile app
            command: |
              yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - .
    publish:
      docker:
        - image: circleci/node:8
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Npm login
            command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - run:
            name: Publish
            command: npm publish

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
